trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
# checkout submodules
- checkout: self
  submodules: true

# build documentation
- task: PowerShell@2
  inputs:
    filePath: 'build/build.ps1'
    arguments: 'no-user no-token no-email 1'