trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
# checkout submodules
- checkout: self
  persistCredentials: true
  submodules: true

# build and deploy documentation
- task: PowerShell@2
  inputs:
    filePath: 'build/build.ps1'
    arguments: '1'